### ISSUE TITLE
Python Errors

### ISSUE THREAD

**Issue by SchellerCyberSecurity** [leebaird/discover#137]
I am getting the below errors after running this on an updated Kali 2019.1 instance.

While running DNSRECON:
Exception in thread Thread-4 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "./dnsrecon.py", line 105, in run
  File "/usr/lib/python2.7/Queue.py", line 168, in get
  File "/usr/lib/python2.7/threading.py", line 334, in wait
<type 'exceptions.TypeError'>: 'NoneType' object is not callable

While running theHarvester:

/usr/local/lib/python3.7/dist-packages/grequests.py:21: MonkeyPatchWarning: Patching more than once will result in the union of all True parameters being patched
  curious_george.patch_all(thread=False, select=False)
     bing                 (10/41)
/usr/local/lib/python3.7/dist-packages/grequests.py:21: MonkeyPatchWarning: Patching more than once will result in the union of all True parameters being patched
  curious_george.patch_all(thread=False, select=False)

**Comment by L1ghtn1ng** [comment]
The monkey patch warning should be resolved now
