### ISSUE TITLE
Problem with passive mode

### ISSUE THREAD

**Issue by kiuji** [leebaird/discover#159]
I need cancel the process because it has error with DNSRecon, Could you help me?

==================================================================

ARIN
     Email                (1/47)
     Names                (2/47)
     Networks             (3/47)

DNSRecon                  (4/47)
/opt/discover/passive.sh: line 116: /opt/DNSRecon/dnsrecon: No such file or directory

goofile                   (5/47)
^CTraceback (most recent call last):
  File "/opt/discover/mods/goofile.py", line 63, in <module>
    main()
  File "/opt/discover/mods/goofile.py", line 53, in main
    google_dork()
  File "/opt/discover/mods/goofile.py", line 31, in google_dork
    page = requests.get(url, headers=headers)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 300, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 156, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
KeyboardInterrupt

Terminating...

All data will be saved in /root/data/cancelled-22:17:41.

Saving complete.

**Comment by kiuji** [comment]
this error too 

ModuleNotFoundError: No module named 'uvloop'

**Comment by kiuji** [comment]
theHarvester
     baidu                (9/47)
Traceback (most recent call last):
  File "./theHarvester.py", line 7, in <module>
    import uvloop
ModuleNotFoundError: No module named 'uvloop'
     bing                 (10/47)
Traceback (most recent call last):
  File "./theHarvester.py", line 7, in <module>
    import uvloop
ModuleNotFoundError: No module named 'uvloop'
     bingapi              (11/47)
Traceback (most recent call last):
  File "./theHarvester.py", line 7, in <module>
    import uvloop
ModuleNotFoundError: No module named 'uvloop'
     bufferoverun         (12/47)
Traceback (most recent call last):
  File "./theHarvester.py", line 7, in <module>
    import uvloop
ModuleNotFoundError: No module named 'uvloop'
     certspotter          (13/47)
Traceback (most recent call last):
  File "./theHarvester.py", line 7, in <module>
    import uvloop
ModuleNotFoundError: No module named 'uvloop'
     crtsh                (14/47)

**Comment by leebaird** [comment]
Typo on my end. I apologize. A git pull should now fix the issue.

**Comment by L1ghtn1ng** [comment]
sudo pip3 install uvloop
________________________________
