### ISSUE TITLE
passive recon problem

### ISSUE THREAD

**Issue by shanow7** [leebaird/discover#166]
hi I've this prloblem

Domain:  agrohandlowiec.com.pl

==================================================================

Amass                     (1/48)
/opt/discover/passive.sh: line 98: amass: command not found

ARIN
     Email                (2/48)
     Names                (3/48)
     Networks             (4/48)

DNSRecon                  (5/48)
dnsrecon.py:208: DeprecationWarning: please use dns.resolver.Resolver.resolve() instead
  answers = res.query(test_name, record_type, tcp=True)
dnsrecon.py:805: DeprecationWarning: please use dns.resolver.Resolver.resolve() instead
  answer = res._res.query(domain, 'DNSKEY')
Traceback (most recent call last):
  File "dnsrecon.py", line 1691, in <module>
    main()
  File "dnsrecon.py", line 1510, in main
    std_enum_records = general_enum(res, domain, xfr, bing, yandex, spf_enum, do_whois, do_crt, zonewalk,
  File "dnsrecon.py", line 934, in general_enum
    bind_ver = check_bindversion(res, ns_rcrd[2], res._res.timeout)
  File "dnsrecon.py", line 847, in check_bindversion
    print_status(f"\t Bind Version for {ns_server} {response.answer[0].items[0].strings[0]}")
KeyError: 0

dnstwist                  (6/48)
/opt/dnstwist/dnstwist.py:521: DeprecationWarning: please use dns.resolver.Resolver.resolve() instead
  domain['dns-ns'] = self.__answer_to_list(resolv.query(domain['domain-name'], rdtype=dns.rdatatype.NS))
/opt/dnstwist/dnstwist.py:534: DeprecationWarning: please use dns.resolver.Resolver.resolve() instead
  domain['dns-a'] = self.__answer_to_list(resolv.query(domain['domain-name'], rdtype=dns.rdatatype.A))
/opt/dnstwist/dnstwist.py:543: DeprecationWarning: please use dns.resolver.Resolver.resolve() instead
  domain['dns-aaaa'] = self.__answer_to_list(resolv.query(domain['domain-name'], rdtype=dns.rdatatype.AAAA))
/opt/dnstwist/dnstwist.py:553: DeprecationWarning: please use dns.resolver.Resolver.resolve() instead
  domain['dns-mx'] = self.__answer_to_list(resolv.query(domain['domain-name'], rdtype=dns.rdatatype.MX))
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/dnstwist/dnstwist.py", line 509, in run
    resolv = dns.resolver.Resolver()
  File "/usr/local/lib/python3.8/dist-packages/dns/resolver.py", line 695, in __init__
    self.read_resolv_conf(filename)
  File "/usr/local/lib/python3.8/dist-packages/dns/resolver.py", line 781, in read_resolv_conf
    raise NoResolverConfiguration
dns.resolver.NoResolverConfiguration: Resolver configuration could not be read or specified no nameservers.
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-5:
Traceback (most recent call last):
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/dnstwist/dnstwist.py", line 509, in run
    resolv = dns.resolver.Resolver()
  File "/usr/local/lib/python3.8/dist-packages/dns/resolver.py", line 695, in __init__
    self.run()
  File "/opt/dnstwist/dnstwist.py", line 509, in run
    self.run()
    resolv = dns.resolver.Resolver()
  File "/usr/local/lib/python3.8/dist-packages/dns/resolver.py", line 695, in __init__
  File "/opt/dnstwist/dnstwist.py", line 509, in run
    self.read_resolv_conf(filename)
  File "/usr/local/lib/python3.8/dist-packages/dns/resolver.py", line 781, in read_resolv_conf
    self.read_resolv_conf(filename)
    resolv = dns.resolver.Resolver()
  File "/usr/local/lib/python3.8/dist-packages/dns/resolver.py", line 695, in __init__
    raise NoResolverConfiguration
dns.resolver.NoResolverConfiguration: Resolver configuration could not be read or specified no nameservers.
  File "/usr/local/lib/python3.8/dist-packages/dns/resolver.py", line 781, in read_resolv_conf
    self.read_resolv_conf(filename)
    raise NoResolverConfiguration
  File "/usr/local/lib/python3.8/dist-packages/dns/resolver.py", line 781, in read_resolv_conf
dns.resolver.NoResolverConfiguration: Resolver configuration could not be read or specified no nameservers.
    raise NoResolverConfiguration
dns.resolver.NoResolverConfiguration: Resolver configuration could not be read or specified no nameservers.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/dnstwist/dnstwist.py", line 509, in run
    resolv = dns.resolver.Resolver()
  File "/usr/local/lib/python3.8/dist-packages/dns/resolver.py", line 695, in __init__
    self.read_resolv_conf(filename)
  File "/usr/local/lib/python3.8/dist-packages/dns/resolver.py", line 781, in read_resolv_conf
    raise NoResolverConfiguration
dns.resolver.NoResolverConfiguration: Resolver configuration could not be read or specified no nameservers.
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/dnstwist/dnstwist.py", line 509, in run
    resolv = dns.resolver.Resolver()
  File "/usr/local/lib/python3.8/dist-packages/dns/resolver.py", line 695, in __init__
    self.read_resolv_conf(filename)
  File "/usr/local/lib/python3.8/dist-packages/dns/resolver.py", line 781, in read_resolv_conf
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/dnstwist/dnstwist.py", line 509, in run
    self.run()
  File "/opt/dnstwist/dnstwist.py", line 509, in run
    self.run()
    raise NoResolverConfiguration
dns.resolver.NoResolverConfiguration: Resolver configuration could not be read or specified no nameservers.
    resolv = dns.resolver.Resolver()
    resolv = dns.resolver.Resolver()
  File "/usr/local/lib/python3.8/dist-packages/dns/resolver.py", line 695, in __init__
  File "/usr/local/lib/python3.8/dist-packages/dns/resolver.py", line 695, in __init__
  File "/opt/dnstwist/dnstwist.py", line 509, in run
    self.read_resolv_conf(filename)
  File "/usr/local/lib/python3.8/dist-packages/dns/resolver.py", line 781, in read_resolv_conf
    resolv = dns.resolver.Resolver()
  File "/usr/local/lib/python3.8/dist-packages/dns/resolver.py", line 695, in __init__
    self.read_resolv_conf(filename)
  File "/usr/local/lib/python3.8/dist-packages/dns/resolver.py", line 781, in read_resolv_conf
    raise NoResolverConfiguration
dns.resolver.NoResolverConfiguration: Resolver configuration could not be read or specified no nameservers.
    raise NoResolverConfiguration
dns.resolver.NoResolverConfiguration: Resolver configuration could not be read or specified no nameservers.
    self.read_resolv_conf(filename)
  File "/usr/local/lib/python3.8/dist-packages/dns/resolver.py", line 781, in read_resolv_conf
    raise NoResolverConfiguration
dns.resolver.NoResolverConfiguration: Resolver configuration could not be read or specified no nameservers.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/dnstwist/dnstwist.py", line 509, in run
    resolv = dns.resolver.Resolver()
  File "/usr/local/lib/python3.8/dist-packages/dns/resolver.py", line 695, in __init__
    self.read_resolv_conf(filename)
  File "/usr/local/lib/python3.8/dist-packages/dns/resolver.py", line 781, in read_resolv_conf
    raise NoResolverConfiguration
dns.resolver.NoResolverConfiguration: Resolver configuration could not be read or specified no nameservers.

can you help?

**Comment by L1ghtn1ng** [comment]
Please make sure you run update.sh that should fix your issues
________________________________

**Comment by shanow7** [comment]
I run sudo ./update.sh nothing changed

**Comment by L1ghtn1ng** [comment]
What is the os you are running and version?
________________________________

**Comment by shanow7** [comment]
VM, debian (64-bit)

**Comment by L1ghtn1ng** [comment]
Ah, you need to be running Kali for it to work properly, kali.org is the URL you need
________________________________

**Comment by shanow7** [comment]
thx
